coverage:
  status:
    project:
      default:
        target: 75%
        threshold: 5%
      service:
        paths:
          - "src/main/java/com/myproject/userservice/service/**"
        target: 80%
        threshold: 5%
      controller:
        paths:
          - "src/main/java/com/myproject/userservice/controller/**"
        target: 80%
        threshold: 5%

    patch:
      default:
        target: 80%
        threshold: 5%