CREATE TABLE IF NOT EXISTS user_role
(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,

    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES "user" (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES "role" (id) ON UPDATE CASCADE ON DELETE RESTRICT
);